
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pan-plugin-crole-tf
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - nodes
  - pods
  - services
  - secrets
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pan-plugin-crb-tf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pan-plugin-crole-tf
subjects:
- kind: ServiceAccount
  name: pan-plugin-user-tf
  namespace: kube-system
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pan-plugin-user-tf
  namespace: kube-system
  labels:
    app: pan-plugin
